name: Morning build and test

on:
  schedule:
    - cron: '0 22 * * 1,2'
    - cron: '0 22 * * 3,4'

jobs:
 morning_greeting:
  runs-on: ubuntu-latest
  steps:
  
   - name: Say Hi
     run: echo 'Hi'
    
   - name: K aze
     run: echo 'K aze'
