name: Morning build and test

on:
  schedule:
   - cron: '10 12 * * *'

jobs:
 morning_greeting:
  runs-on: ubuntu-latest
  steps:
  
   - name: Say Hi
     run: echo 'Hi'
    
   - name: K aze
     run: echo 'K aze'
